apiVersion: v1
kind: ConfigMap
metadata:
  name: gopay-service-config
data:
  ENV: "production"

  HTTP_ADDR: ":8080"
  HTTP_READ_TIMEOUT: "5s"
  HTTP_WRITE_TIMEOUT: "10s"
  HTTP_SHUTDOWN_TIMEOUT: "30s"

  DATABASE_MIGRATIONS_PATH: "file:///migrations"
  DATABASE_MAX_CONNS: "20"
  DATABASE_MIN_CONNS: "5"

  REDIS_ADDR: "redis:6379"
  REDIS_NAMESPACE: "gopay-service"