apiVersion: v1
kind: Service
metadata:
  name: gopay-service
  labels:
    app: gopay-service
spec:
  type: ClusterIP
  selector:
    app: gopay-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
