apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gopay-service.fullname" . }}
  labels:
    {{- include "gopay-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-dsn: {{ .Values.database.dsn | required "database.dsn is required" | quote }}
