apiVersion: v1
kind: Service
metadata:
  name: {{ include "gopay-service.fullname" . }}
  labels:
    {{- include "gopay-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector:
    app: {{ include "gopay-service.name" . }}
